### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by tockudex** [LyrinoxTechnologies/glava-ridged#1]
Hello,
I've been following the project from afar, but haven't noticed any recent activity.
Is the project still alive ?

**Comment by VetheonDevelops** [comment]
> Hello, I've been following the project from afar, but haven't noticed any recent activity. Is the project still alive ?

Well first, if you're following from Github, this is the wrong place. I dont post my code here anymore.

Second, it is, and it isn't. There's a known issue currently with the name of a library having changed (because the Arch Linux maintainers like to rename packages all the time) but there is no real code that needs to be changed, just the depend name.

Third, I am a one man operation, and I maintain GLava out of love for the project and nothing more. I also run an entire business on top of maintaining my OSPs, so lately OSPs have taken a back burner to paying projects, for obvious reasons.

**Comment by tockudex** [comment]
I did not intend to “sound” rude.

As the project is still available on GitHub, I assumed it was the right place to ask my question, especially since, what appears to be, [your main git website](https://git.pixelridgesoftworks.com) is currently not accessible.
